
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.testlang.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 17;
  public static final int POST = 12;
  public static final int SEMICOLON = 19;
  public static final int RANGE = 24;
  public static final int RPAREN = 23;
  public static final int RBRACE = 21;
  public static final int TEST = 6;
  public static final int STATUS = 8;
  public static final int IN = 15;
  public static final int EXPECT = 7;
  public static final int IDENTIFIER = 25;
  public static final int CAPTURE = 16;
  public static final int LPAREN = 22;
  public static final int LBRACE = 20;
  public static final int PUT = 13;
  public static final int CONTAINS = 10;
  public static final int STRING = 26;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LET = 5;
  public static final int EQ = 18;
  public static final int BODY = 9;
  public static final int HEADER = 4;
  public static final int BASE_URL = 3;
  public static final int DELETE = 14;
  public static final int CONFIG = 2;
  public static final int GET = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONFIG",
  "BASE_URL",
  "HEADER",
  "LET",
  "TEST",
  "EXPECT",
  "STATUS",
  "BODY",
  "CONTAINS",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "IN",
  "CAPTURE",
  "FROM",
  "EQ",
  "SEMICOLON",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "RANGE",
  "IDENTIFIER",
  "STRING",
  "NUMBER"
  };
}

